spring:
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: beans, conditions, configprops, env, flyway, httptrace, metrics, mappings, health, info
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    db:
      enabled: true